CREATE TABLE campuses
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    code   VARCHAR(255)                                        NOT NULL,
    name   VARCHAR(255)                                        NOT NULL,
    active BOOLEAN                                             NOT NULL
);
ALTER TABLE campuses
    ADD CONSTRAINT uq_campuses_code UNIQUE (code)