CREATE TABLE academic_programs
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    code   VARCHAR(255)                                        NOT NULL,
    name   VARCHAR(255)                                        NOT NULL,
    active BOOLEAN                                             NOT NULL
);
ALTER TABLE academic_programs
    ADD CONSTRAINT uq_academic_programs_code UNIQUE (code)