CREATE TABLE users
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    national_id         VARCHAR(20)                                         NOT NULL,
    first_name          VARCHAR(100)                                        NOT NULL,
    last_name           VARCHAR(100)                                        NOT NULL,
    email               VARCHAR(150)                                        NOT NULL,
    phone               VARCHAR(20)                                         NOT NULL,
    campus_id           BIGINT,
    academic_program_id BIGINT,
    semester            INTEGER,
    role                VARCHAR(30)                                         NOT NULL,
    created_at          TIMESTAMP                                           NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMP,
    active              BOOLEAN                                             NOT NULL DEFAULT TRUE
);
ALTER TABLE users
    ADD CONSTRAINT uq_users_email UNIQUE (email);
ALTER TABLE users
    ADD CONSTRAINT uq_users_national_id UNIQUE (national_id);
ALTER TABLE users
    ADD CONSTRAINT fk_users_academic_program FOREIGN KEY (academic_program_id) REFERENCES academic_programs (id);
ALTER TABLE users
    ADD CONSTRAINT fk_users_campus FOREIGN KEY (campus_id) REFERENCES campuses (id)