CREATE TABLE role_access_codes
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    role        VARCHAR(30)                                         NOT NULL,
    code        VARCHAR(50)                                         NOT NULL,
    valid_from  DATE                                                NOT NULL,
    valid_until DATE                                                NOT NULL,
    active      BOOLEAN                                             NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMP                                           NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_role_code UNIQUE (code),
    CONSTRAINT chk_valid_dates CHECK (valid_until >= valid_from)
)