CREATE TABLE accompaniment_courses
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    code   VARCHAR(255)                                        NOT NULL,
    name   VARCHAR(255)                                        NOT NULL,
    active BOOLEAN                                             NOT NULL
);
ALTER TABLE accompaniment_courses
    ADD CONSTRAINT uq_accompaniment_courses_code UNIQUE (code)