CREATE TABLE service_types
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    code   VARCHAR(255)                                        NOT NULL,
    name   VARCHAR(255)                                        NOT NULL,
    active BOOLEAN                                             NOT NULL
);
ALTER TABLE service_types
    ADD CONSTRAINT uq_service_types_code UNIQUE (code)