CREATE TABLE attendances
(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,

  session_code VARCHAR(255) NOT NULL,
  user_id BIGINT NOT NULL,
  service_type_id BIGINT NOT NULL,
  course_id BIGINT,
  estimated_hours DECIMAL(10,2) NOT NULL,
  authorization_required BOOLEAN NOT NULL,
  comments VARCHAR(1000),
  created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL
);
ALTER TABLE attendances ADD CONSTRAINT uq_attendances_session_code UNIQUE(session_code) ;
ALTER TABLE attendances ADD CONSTRAINT fk_attendances_course FOREIGN KEY(course_id) REFERENCES ACCOMPANIMENT_COURSES(id) ;
ALTER TABLE attendances ADD CONSTRAINT fk_attendances_service_type FOREIGN KEY(service_type_id) REFERENCES SERVICE_TYPES(id) ;
ALTER TABLE attendances ADD CONSTRAINT fk_attendances_user FOREIGN KEY(user_id) REFERENCES USERS(id);